ArcaneTinmen/Models/Product.cs
namespace ArcaneTinmen.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("product")]
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            OrderItem = new HashSet<OrderItem>();
        }

        public int ProductId { get; set; }

        [StringLength(25)]
        public string Name { get; set; }

        public decimal Price { get; set; }

        [StringLength(25)]
        public string Image { get; set; }

        [Column(TypeName = "text")]
        public string Description { get; set; }

        [Column(TypeName = "text")]
        public string Specs { get; set; }

        public int SizeId { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItem { get; set; }

        public virtual Size Size { get; set; }
        
        //Constructor
        public Product(int productid, decimal price, string image, string description, string specs, int sizeid)
        {
            ProductId = productid;
            Price = price;
            Image = image;
            Description = description;
            Specs = specs;
            SizeId = sizeid;
        }
    }
}

ArcaneTinmen/Areas/Admin/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ArcaneTinmen.Models;

namespace ArcaneTinmen.Areas.Admin.Controllers
{
    public class ProductsController : Controller
    {
        private ArcaneTinmenDBContext db = new ArcaneTinmenDBContext();

        // GET: Admin/Products
        public ActionResult Index()
        {
            var product = db.Product.Include(p => p.Size);
            return View(product.ToList());
        }

        // GET: Admin/Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Product.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Admin/Products/Create
        public ActionResult Create()
        {
            ViewBag.SizeId = new SelectList(db.Size, "SizeId", "Name");
            return View();
        }

        // POST: Admin/Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductId,Name,Price,Image,Description,Specs,SizeId")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Product.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.SizeId = new SelectList(db.Size, "SizeId", "Name", product.SizeId);
            return View(product);
        }

        // GET: Admin/Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Product.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.SizeId = new SelectList(db.Size, "SizeId", "Name", product.SizeId);
            return View(product);
        }

        // POST: Admin/Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductId,Name,Price,Image,Description,Specs,SizeId")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.SizeId = new SelectList(db.Size, "SizeId", "Name", product.SizeId);
            return View(product);
        }

        // GET: Admin/Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Product.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Admin/Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Product.Find(id);
            db.Product.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ArcaneTinmen/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ArcaneTinmen.Infrastructure;
using ArcaneTinmen.Models;

namespace ArcaneTinmen.Controllers
{
    public class NavController : Controller
    {
        ArcaneTinmenDBContext db = new ArcaneTinmenDBContext();
        public PartialViewResult Menu(string size = null)
        {
            ViewBag.SelectedSize = size;

            IEnumerable<string> sizes = db.Product
            .Select(x => x.Size.Name)
            .Distinct()
            .OrderBy(x => x);
            return PartialView(sizes);
        }
    }
}

ArcaneTinmen/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ArcaneTinmen.Models;
using ArcaneTinmen.ViewModels;

namespace ArcaneTinmen.Controllers
{
    public class ProductController : Controller
    {

        public int PageSize = 10;
        ArcaneTinmenDBContext db = new ArcaneTinmenDBContext();
        // GET: Product
        public ActionResult Index(string size, int page = 1, string option = "", string search = "")
        {
            IEnumerable<Product> products;
            IEnumerable<Games> games;
            

            if (option == "Name")
            {
                products = db.Product.Where(x => x.Name.Contains(search));
            }
            else
            {
                products = db.Product
                .Where(p => size == null || p.Size.Name == size)
                .OrderBy(p => p.SizeId)
                .Skip((page - 1) * PageSize)
                .Take(PageSize);
            }

            if (size != null)
            {
                games = db.Games
                   .Where(game => game.GameSize
                   .Any(s => s.Size.Name
                    == size));
            }
            else
            {
                games = db.Games.Include("GameSize.Size.Product");
            }

            ProductsListViewModel model = new ProductsListViewModel
            {
                Products = products,
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = size == null ?
                db.Product.Count() :
                db.Product.Where(e => e.Size.Name == size).Count()
                },
                CurrentSize = size,
                Games = games,
                
            };
            return View(model);
        }
    }
}

ArcaneTinmen/Views/Product/Index.cshtml
@using ArcaneTinmen.Models;
@model ArcaneTinmen.ViewModels.ProductsListViewModel

@{
    ViewBag.Title = "BGS: Products";
}
<div class="container">
    <div id="categories" class="col-xs-12">
        <div class="product-holder list hidden-xs">
            @Html.Action("Menu", "Nav")
        </div>
        <div class="product-holder dropdown text-center visible-xs">
            <button id="dLabel" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Choose product
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dLabel">
                <li>@Html.Action("Menu", "Nav")</li>
            </ul>
        </div>
        <div class="searchfield clearfix hidden-xs">
            @using (Html.BeginForm("Index", "Product", FormMethod.Get, new { @class = "form-inline pull-right" }))
            {
                <div class="form-group">
                    <div class="radio-inline" style="display:none;">
                        <label>@Html.RadioButton("option", "Name", true) Name</label>
                    </div>
                </div>
                <div class="form-group">
                    @Html.TextBox("search", null, new { @class = "form-control", @placeholder="Search name or size" })
                </div>
                <input type="submit"
                       name="submit"
                       value="Search"
                       class="btn btn-primary" />

                if (Model.Products.Count() == 0)
                {  <div>Records not found</div>  }
            }
        </div>
    </div>
    <div class="product-info col-xs-12">
        @foreach (Product product in Model.Products)
        {
            <div class="product-single">
                <div class="row">
                    <div class="col-sm-6">
                        <h1 class="visible-xs">@product.Name</h1>
                        <a href="#" class="imgholder" data-toggle="modal" data-target="#lightbox">
                            <div class="img img-100" style="background-image: url('/content/images/@product.Image')">
                                <img src="/content/images/@product.Image" />
                            </div>
                            <div class="search">
                                <span class="glyphicon glyphicon-search"></span>
                            </div>
                        </a>
                    </div>
                    <div class="col-sm-6">
                        <h1 class="hidden-xs">@product.Name</h1>
                        <h2>@product.Price kr</h2>
                        @using (Html.BeginForm("AddToCart", "Cart"))
                {
                            @Html.Hidden("ProductId", product.ProductId)
                            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                            <input type="submit" class="add-cart btn btn-success" value="Add to cart" />
                        }
                        @using (Html.BeginForm("Index", "Cart"))
                {
                            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                            <input type="submit" class="view-cart btn btn-warning" value="View Cart" />
                        }
                        <div class="specs">
                            <h3>Specifications</h3>
                            <table class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th>
                                            @product.Size.Name sized sleeve
                                        </th>
                                        <th>
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>

                                    @{
                                        string[] specs = product.Specs.Split('x');
                                        foreach (string spec in specs)
                                        {
                                            <tr>
                                                <td>
                                                    @spec mm
                                                </td>
                                            </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="games-compat col-xs-12 col-sm-6 col-sm-push-6">
                        <h3>Game compatibility</h3>
                        <ul>
                            @foreach (Games g in Model.Games)     
                                {
                                <li><i class="fa fa-check"></i> @g.Name</li>
                                }
                        </ul>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-sm-pull-6">
                        <h3>Description</h3>
                        <p>@product.Description</p>
                    </div>
                </div>
                <hr />
            </div>
        }
    </div>
</div>